---
title: "`r params$sanctuary`"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    self_contained: false
    lib_dir: "docs/libs"
    includes:
      in_header: "./_navbar.html"
    css: "_style.css"
params:
  # nms: "GRNMS"
  # sanctuary: "Gray's Reef"
  # nms: "MBNMS-david"
  # sanctuary: "Monterey Bay - Davidson Seamount"
  # nms: "MNMS"
  # sanctuary: "Monitor"
  nms: "MBNMS-david"
  sanctuary: "Monterey Bay - Davidson Seamount"
  
editor_options: 
  chunk_output_type: console
---

```{r setup}
# params <- list(
#   nms       = "MBNMS-david",
#   sanctuary = "Monterey Bay - Davidson Seamount")

librarian::shelf(
  dplyr, glue, here, mapview, readr, sf, stringr,
  marinebon/extractr)
# devtools::load_all("~/Github/marinebon/extractr")
source(here("scripts/functions.R"))

sanctuaries <- readRDS(here("data/sanctuaries.rds"))

# TODO: change "datasets" to "variables"
datasets <- read_csv(here("data/datasets.csv"))
datasets_ed <- datasets |> 
  filter(type == "erddap")
datasets_nc <- datasets |> 
  filter(type == "nc")
# TODO: add y_label, ∆ height CRW_SST

write_metadata <- function(
    sanctuary_nms, dataset_var, dataset_url,
    prefix = "", suffix = ""){

  cat(glue('
  <details>
  <summary><span style="color: #737373; font-size: 12px">Metadata</span></summary>
  {prefix}
  The ERDDAP dataset for [{dataset_var}]({dataset_url}) was extracted using [get_data.R](https://github.com/noaa-onms/climate-dashboard/blob/main/scripts/get_data.R) for the {params$sanctuary} polygon and output to [{params$nms}.csv](https://raw.githubusercontent.com/noaa-onms/climate-dashboard/main/data/{dataset_var}/{params$nms}.csv), which gets visualized below using [`extractr::plot_ts()`](https://marinebon.github.io/extractr/reference/plot_ts.html).
  {suffix}
  </details> 
  '))
}
```

# Map {.sidebar data-width=200}

```{r}
# params <- list(
#   nms = "GRNMS",
#   sanctuary = "Gray's Reef")

sanctuaries |>
  filter(sanctuary == params$sanctuary) |>
  map_sanctuary()
```

# Climatological

### Sea Surface Temperature {data-height=300}

```{r, results='asis'}
ds_var <- "sst"
ds <- filter(datasets_ed, var == !!ds_var)
write_metadata(params$nms, ds_var, ds$url)
```
    
```{r}
ts_csv <- here(glue("data/{ds_var}/{params$nms}.csv"))
plot_ts(ts_csv, fld_sd = "sd", color = ds$plot_color, label = ds$plot_label)
```

### Chlorophyll {data-height=300}
    
```{r, results='asis'}
ds_var <- "chlorophyll"
ds <- filter(datasets_ed, var == !!ds_var)
write_metadata(params$nms, ds_var, ds$url)
```

```{r}
ts_csv <- here(glue("data/{ds_var}/{params$nms}.csv"))
plot_ts(ts_csv, fld_sd = "sd", color = ds$plot_color, label = ds$plot_label)
```

### Coral Reef Watch {data-height=300}

```{r, results='asis'}
ds_var <- "CRW_SST"
ds <- filter(datasets_ed, var == !!ds_var)
write_metadata(params$nms, ds_var, ds$url)
```

```{r}
ts_csv <- here(glue("data/{ds_var}/{params$nms}.csv"))
# TODO: resolve issues with Monitor being too small to have data
has_data <- sum(!is.na(read_csv(ts_csv, show_col_types=F) |> pull(mean))) > 0
```

```{r}
#| eval: !expr has_data
plot_ts(ts_csv, fld_sd = "sd", color = ds$plot_color, label = ds$plot_label)
```

# Forecast

```{r, results='asis'}
clim_csv <- glue(here("data/Climate_projections/{params$nms}_CESM2LE_data_1850-2100_mean_stdev_annual.csv"))

var <- "sst"
if (file.exists(clim_csv))
  nc_meta(var)
```

```{r}
#| eval: !expr file.exists(clim_csv)
nc_plot(var)
```

```{r, results='asis'}
var <- "chl"
if (file.exists(clim_csv))
  nc_meta(var)
```

```{r}
#| eval: !expr file.exists(clim_csv)
nc_plot(var)
```

```{r, results='asis'}
var <- "ph"
if (file.exists(clim_csv))
  nc_meta(var)
```

```{r}
#| eval: !expr file.exists(clim_csv)
nc_plot(var)
```


```{r, results='asis'}
var <- "sss"
if (file.exists(clim_csv))
  nc_meta(var)
```

```{r}
#| eval: !expr file.exists(clim_csv)
nc_plot(var)
```


```{r, results='asis'}
var <- "mld"
if (file.exists(clim_csv))
  nc_meta(var)
```

```{r}
#| eval: !expr file.exists(clim_csv)
nc_plot(var)
```

# Physical-chemical

### Chart P.1

```{r}
```

### Chart P.2

```{r}
```


# Biological

### Chart B.1

```{r}
```

### Chart B.2

```{r}
```

# Human Dimensions

### Chart H.1

```{r}
```

### Chart H.2

```{r}
```

